Portfolio: finish mobile version
Umuhan/portfolio-project pull request #2
Opened 2023-03-24 15:01 UTC by Umuhan

In this pull request i did:
- [ ] Add works section.
- [ ] Add about section. 
- [ ] Add style for both sections.

2023-03-24 15:45 UTC, RaoAkif requested changes
## STATUS: REQUIRED CHANGES ♻️

Hi @Umuhan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Required Changes ♻️
_Check the comments under the review._
<img src="https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966" />

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 15:45 UTC, RaoAkif commented on index.html
> +          <h2 class="heading-title">My Recent works</h2>
[OPTIONAL] You can capitalize the word "works" from the heading "My Recent Works", to stay consistent with the Figma file. It seems not a big issue, but being consistent in overall font decisions make the design beautiful.

2023-03-24 15:45 UTC, RaoAkif commented on css/style.css
> +  font-size: 0.9rem;
As per the Figma file, the size of this `lang` tag text is `1.2rem`, but in you design it is `font-size: 0.9rem;`. Kindly update the font-size and stay consistent with the provided FIGMA design.

2023-03-24 15:45 UTC, RaoAkif commented on css/style.css
> +  font-size: 1.8rem;
As per the Figma file, the size of this `btn` class font text is 1.7rem, but in you design it is font-size: 1.8rem;. Kindly update the font-size and stay consistent with the provided FIGMA design.

2023-03-24 15:45 UTC, RaoAkif commented on index.html
> +            alt="Language icon"
The size of these section in Figma design is
```
height: 316px;
width: 327px;
```

But you have put the size as:
```
height: 325px;
width: 224px;
```
Kindly update the design, as per the design given to stay consistent.

2023-03-25 10:35 UTC, Umuhan commented on index.html
> +            alt="Language icon"
Done

2023-03-25 10:35 UTC, Umuhan commented on css/style.css
> +  font-size: 1.8rem;
Done.

2023-03-25 10:36 UTC, Umuhan commented on css/style.css
> +  font-size: 1.8rem;
Done.

2023-03-25 10:36 UTC, Umuhan commented on index.html
> +          <h2 class="heading-title">My Recent works</h2>
Done.

2023-03-25 10:36 UTC, Umuhan commented on css/style.css
> +  font-size: 0.9rem;
Done.

2023-03-25 10:47 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Umuhan 

Your project is complete! Great job for making the changes suggested by the previous reviewer 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Figma design well followed
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/tKKF42WroJXpOucTY9/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 10:48 UTC, merged